-- Create database (if not already created)
CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

-- TABLE: AUTHORS
CREATE TABLE IF NOT EXISTS authors (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIRTH_YEAR INT
);

-- TABLE: BOOKS
CREATE TABLE IF NOT EXISTS books (
    BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT,
    PRICE DECIMAL(10, 2) NOT NULL,
    PUBLICATION_YEAR INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES authors(AUTHOR_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- TABLE: CUSTOMERS
CREATE TABLE IF NOT EXISTS customers (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    PHONE VARCHAR(20)
);

-- TABLE: ORDERS
CREATE TABLE IF NOT EXISTS orders (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE DEFAULT CURRENT_DATE,
    TOTAL_AMOUNT DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(CUSTOMER_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- TABLE: ORDER_DETAILS
CREATE TABLE IF NOT EXISTS order_details (
    ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES orders(ORDER_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES books(BOOK_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);